In [1]:
import numpy
import torch

## 创建Tensor

In [5]:
#创建未初始化的Tensor
x=torch.empty(5,3)
print(x)

tensor([[1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38],
        [1.1112e-38, 1.0561e-38, 9.9184e-39]])


In [6]:
#随机初始化
x=torch.rand(5,3)
print(x)

tensor([[0.6589, 0.4637, 0.6796],
        [0.8463, 0.8002, 0.4982],
        [0.1946, 0.1563, 0.1627],
        [0.5215, 0.1949, 0.4019],
        [0.1248, 0.4759, 0.9565]])


In [7]:
#Long型全0的Tensor
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
#根据数据创建
x=torch.tensor([5,3,5.5])
print(x)

tensor([5.0000, 3.0000, 5.5000])


In [9]:
#还可以通过现有的Tensor来创建，此方法会默认重用输入Tensor的一些属性，例如数据类型，除非自定义数据类型。
x=x.new_ones(5,3,dtype=torch.float64)
print(x)
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.5872, -1.8133,  1.6661],
        [-0.6300, -1.2444,  0.5798],
        [ 0.9687, -0.3886,  1.6252],
        [ 0.3000,  0.0670, -0.4707],
        [-0.9366,  0.7646,  1.1399]])


In [12]:
#Tensor的形状
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


# 操作

In [14]:
#加法
y=torch.rand(5,3)
print(x+y)

tensor([[-2.2844, -1.4056,  2.4371],
        [ 0.2555, -0.8432,  0.8808],
        [ 1.8159,  0.2977,  1.8836],
        [ 0.6483,  0.9414,  0.1167],
        [-0.6311,  1.6994,  1.9107]])


In [15]:
print(torch.add(x,y))

tensor([[-2.2844, -1.4056,  2.4371],
        [ 0.2555, -0.8432,  0.8808],
        [ 1.8159,  0.2977,  1.8836],
        [ 0.6483,  0.9414,  0.1167],
        [-0.6311,  1.6994,  1.9107]])


In [16]:
#指定输出
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-2.2844, -1.4056,  2.4371],
        [ 0.2555, -0.8432,  0.8808],
        [ 1.8159,  0.2977,  1.8836],
        [ 0.6483,  0.9414,  0.1167],
        [-0.6311,  1.6994,  1.9107]])


In [17]:
y.add_(x)
print(y)

tensor([[-2.2844, -1.4056,  2.4371],
        [ 0.2555, -0.8432,  0.8808],
        [ 1.8159,  0.2977,  1.8836],
        [ 0.6483,  0.9414,  0.1167],
        [-0.6311,  1.6994,  1.9107]])


# 索引

In [18]:
y=x[0,:]
y+=1
print(y)
print(x[0,:]) #源tensor也被改了

tensor([-1.5872, -0.8133,  2.6661])
tensor([-1.5872, -0.8133,  2.6661])


# 改变形状

In [19]:
y=x.view(15)
z=x.view(-1,5)
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [20]:
# 注意view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)

In [21]:
x+=1
print(x)
print(y) #也加了1

tensor([[-0.5872,  0.1867,  3.6661],
        [ 0.3700, -0.2444,  1.5798],
        [ 1.9687,  0.6114,  2.6252],
        [ 1.3000,  1.0670,  0.5293],
        [ 0.0634,  1.7646,  2.1399]])
tensor([-0.5872,  0.1867,  3.6661,  0.3700, -0.2444,  1.5798,  1.9687,  0.6114,
         2.6252,  1.3000,  1.0670,  0.5293,  0.0634,  1.7646,  2.1399])


In [23]:
#使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor。

In [24]:
x_cp=x.clone().view(15)
x-=1
print(x)
print(x_cp)

tensor([[-2.5872, -1.8133,  1.6661],
        [-1.6300, -2.2444, -0.4202],
        [-0.0313, -1.3886,  0.6252],
        [-0.7000, -0.9330, -1.4707],
        [-1.9366, -0.2354,  0.1399]])
tensor([-1.5872, -0.8133,  2.6661, -0.6300, -1.2444,  0.5798,  0.9687, -0.3886,
         1.6252,  0.3000,  0.0670, -0.4707, -0.9366,  0.7646,  1.1399])


In [25]:
#另外一个常用的函数就是item(), 它可以将一个标量Tensor转换成一个Python number
x=torch.randn(1)
print(x)
print(x.item())

tensor([0.6874])
0.6874387264251709


# 广播机制

In [27]:
#由于x和y分别是1行2列和3行1列的矩阵，如果要计算x + y，那么x中第一行的2个元素被广播（复制）到了第二行和第三行，而y中第一列的3个元素被广播（复制）到了第二列。如此，就可以对2个3行2列的矩阵按元素相加。
x=torch.arange(1,3).view(1,2)
print(x)
y=torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


# 运算的内存开销

In [28]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y=y+x
print(id(y)==id_before)

False


In [29]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y[:]=y+x
print(id(y)==id_before)

True


In [30]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
torch.add(x,y,out=y)
print(id(y)==id_before)

True


# Tensor和NumPy相互转换

In [31]:
a=torch.ones(5)
b=a.numpy()
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [32]:
a+=1
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [33]:
b+=1
print(a,b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [34]:
import numpy as np

# NumPy数组转Tensor

In [35]:
a=np.ones(5)
b=torch.from_numpy(a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [36]:
a+=1
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [37]:
b+=1
print(a,b)

[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [38]:
c=torch.tensor(a)
a+=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# Tensor on GPU

In [39]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
